server:
  port: 9001
  
spring:  application:    name: zuul
    
eureka:  client:    service-url:      defaultZone: http://localhost:9000/eureka
      
zuul:  routes:    user:
      service-id: user-provider           #用户服务的应用名称
      path: /user/**                      #服务别名
    goods:
      service-id: goods-provider                path: /goods/**    orders: 
      service-id: orders-provider
      path: /orders/**        
    
        
        
                      
         
  